# Generated by Django 5.2 on 2026-02-28 11:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_methode', models.CharField(max_length=50)),
                ('numero_paiement', models.CharField(max_length=50)),
                ('nom_compte', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_created=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenu_journalier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_jours', models.PositiveIntegerField(default=90)),
                ('photo', models.ImageField(upload_to='produits/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('code_parrainage', models.CharField(blank=True, max_length=20, unique=True)),
                ('bonus_parrainage_deja_donne', models.BooleanField(default=False)),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='core.profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('moyen_de_paiement', models.CharField(max_length=50)),
                ('numero_compte', models.CharField(max_length=50)),
                ('preuve_paiement', models.FileField(upload_to='preuve/')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_generees', to='core.profil')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_gagnees', to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='AchatProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('revenu_restant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_reception', models.CharField(max_length=50)),
                ('nom_compte', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil')),
            ],
        ),
        migrations.CreateModel(
            name='RevenuJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.achatproduit')),
            ],
        ),
    ]
