# Generated by Django 5.2 on 2026-03-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='depot',
            name='preuve_paiement',
            field=models.FileField(upload_to='preuves/'),
        ),
    ]
