# Generated by Django 5.2 on 2026-03-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_depot_date_alter_depot_preuve_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profil'),
        ),
    ]
