# Generated by Django 5.2 on 2026-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_depot_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenujournalier',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
