# Generated by Django 5.2 on 2026-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_revenujournalier_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatproduit',
            name='dernier_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
