# Generated by Django 5.2 on 2026-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_achatproduit_dernier_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatproduit',
            name='dernier_paiement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
